frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**/*.js"
          - "src/**/*.css"
          - "src/**/*.html"
          - "landing.html"

backend:
  - changed-files:
      - any-glob-to-any-file:
          - "server/**"
          - "api/**"
          - "controllers/**"
          - "routes/**"
          - "models/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"

UI:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**/*.css"
          - "src/**/*.html"
          - "assets/**"

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
