frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "public/**/*.js"
          - "public/**/*.css"
          - "views/**/*.ejs"
          - "views/**/*.html"

backend:
  - changed-files:
      - any-glob-to-any-file:
          - "api/**"
          - "controllers/**"
          - "routes/**"
          - "models/**"
          - "config/**"
          - "app.js"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"

UI:
  - changed-files:
      - any-glob-to-any-file:
          - "public/css/**"
          - "views/**/*.ejs"

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
